### ISSUE TITLE
Problem using ELMCoxBAR function

### ISSUE THREAD

**Issue by epimedplotly** [whcsu/ELMCoxBAR#1]
I'm trying to fit an ELMCoxBar model but I'm facing the problem as follows:

ELMCoxBarModel <- ELMCoxBAR(x = dt_train[,covariates],   y = surv_var)

error: Mat::init(): requested size is too large
Error in kernmat(x, kerneltype, Kernel_para, NULL) : 
  Mat::init(): requested size is too large 
 

dt_train[,covariates]  is a data.frame with 67550 rows and 70 columns.

Any ideia about what could I do to fix it?

**Comment by whcsu** [comment]
I think it is a memory problem. The data is too big to fit your in computer's memeory. 
Maybe you should  train with a subset of this data.
